# The number of instances of the service that we want to run
replicaCount: 1

# The port(s) that need to be exposed from the associated container
ports:
- name: http
  protocol: TCP
  port: 80

# If this is a service for other services to consume, then you'll also
# need to define the port mapping between the service and the container.
# If the service is callable from the public internet, then you can
# define ingress mappings on the port configuration in order to create
# the ingress rules to support this
service:
  ports:
  - port: 80
    targetPort: http
    ingress:
      #host: blah.com
      path: /
