FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["Web.csproj", "./"]
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
RUN dotnet build "Web.csproj" -c Debug -o /app

FROM build AS publish
RUN dotnet publish "Web.csproj" -c Debug -o /app

FROM base AS final
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Web.dll"]
